import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0002_project_screenplay'),
        ('workflows', '0006_workflow_runtime_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('character', '角色'), ('location', '场景设定'), ('prop', '道具'), ('costume', '服饰'), ('look', '视觉设定'), ('audio', '音频素材'), ('reference', '参考素材')], max_length=20, verbose_name='实体类型')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('reference_data', models.JSONField(blank=True, default=dict, verbose_name='参考资料')),
                ('continuity_data', models.JSONField(blank=True, default=dict, verbose_name='连续性基准')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_entities', to='projects.project', verbose_name='项目')),
            ],
            options={'db_table': 'production_entities', 'ordering': ['entity_type', 'name']},
        ),
        migrations.CreateModel(
            name='ProductionScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=1, verbose_name='场次')),
                ('name', models.CharField(max_length=255, verbose_name='场景名称')),
                ('synopsis', models.TextField(blank=True, default='', verbose_name='场景概要')),
                ('time_of_day', models.CharField(blank=True, default='', max_length=50, verbose_name='时间')),
                ('interior_exterior', models.CharField(blank=True, default='', max_length=20, verbose_name='内外景')),
                ('continuity_data', models.JSONField(blank=True, default=dict, verbose_name='连续性基准')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('canvas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_scenes', to='workflows.workflowcanvas', verbose_name='画板')),
                ('location', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_scenes', to='workflows.productionentity', verbose_name='场景设定')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_scenes', to='projects.project', verbose_name='项目')),
            ],
            options={'db_table': 'production_scenes', 'ordering': ['number', 'created_at']},
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=1, verbose_name='镜号')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='镜头标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='画面描述')),
                ('prompt', models.TextField(blank=True, default='', verbose_name='生成提示词')),
                ('shot_size', models.CharField(choices=[('extreme_wide', '大远景'), ('wide', '远景'), ('full', '全景'), ('medium', '中景'), ('close_up', '近景'), ('extreme_close_up', '特写')], default='medium', max_length=30, verbose_name='景别')),
                ('camera_angle', models.CharField(blank=True, default='eye_level', max_length=100, verbose_name='机位')),
                ('focal_length_mm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='焦段(mm)')),
                ('camera_movement', models.CharField(blank=True, default='static', max_length=100, verbose_name='运镜')),
                ('duration_seconds', models.DecimalField(decimal_places=3, default=5, max_digits=7, verbose_name='时长(秒)')),
                ('frame_rate', models.DecimalField(decimal_places=3, default=24, max_digits=7, verbose_name='帧率')),
                ('aspect_ratio', models.CharField(default='16:9', max_length=20, verbose_name='画幅')),
                ('pacing', models.CharField(choices=[('slow', '舒缓'), ('normal', '正常'), ('fast', '快速')], default='normal', max_length=20, verbose_name='节奏')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '待生成'), ('approved', '已确认')], default='draft', max_length=20, verbose_name='状态')),
                ('canvas_node_key', models.CharField(blank=True, default='', max_length=100, verbose_name='画布节点键')),
                ('continuity_data', models.JSONField(blank=True, default=dict, verbose_name='连续性状态')),
                ('is_locked', models.BooleanField(default=False, verbose_name='已锁定')),
                ('locked_snapshot', models.JSONField(blank=True, default=dict, verbose_name='锁定快照')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('canvas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='workflows.workflowcanvas', verbose_name='画板')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='workflows.productionscene', verbose_name='场景')),
            ],
            options={'db_table': 'production_shots', 'ordering': ['scene__number', 'number', 'created_at']},
        ),
        migrations.CreateModel(
            name='ShotEntityBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_data', models.JSONField(blank=True, default=dict, verbose_name='镜头内状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_bindings', to='workflows.productionentity')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_bindings', to='workflows.shot')),
            ],
            options={'db_table': 'shot_entity_bindings'},
        ),
        migrations.AddField(model_name='shot', name='entities', field=models.ManyToManyField(related_name='shots', through='workflows.ShotEntityBinding', to='workflows.productionentity')),
        migrations.CreateModel(
            name='ShotReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_type', models.CharField(choices=[('first_frame', '首帧'), ('last_frame', '尾帧'), ('keyframe', '关键帧'), ('reference_video', '参考视频')], max_length=30, verbose_name='参考类型')),
                ('url', models.URLField(max_length=1000, verbose_name='资源地址')),
                ('frame_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='帧时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='workflows.shot')),
            ],
            options={'db_table': 'shot_references', 'ordering': ['sort_order', 'created_at']},
        ),
        migrations.CreateModel(
            name='ShotTake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Take 序号')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('rendering', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('media_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='视频地址')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='缩略图')),
                ('model_key', models.CharField(blank=True, default='', max_length=255, verbose_name='模型')),
                ('generation_data', models.JSONField(blank=True, default=dict, verbose_name='生成参数')),
                ('is_final', models.BooleanField(default=False, verbose_name='最终 Take')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='workflows.shot')),
            ],
            options={'db_table': 'shot_takes', 'ordering': ['number', 'created_at']},
        ),
        migrations.CreateModel(
            name='ContinuityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('character', '人物'), ('costume', '服饰'), ('prop', '道具'), ('lighting', '光线'), ('spatial', '空间位置'), ('action', '动作衔接')], max_length=20, verbose_name='类别')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('error', '错误')], default='warning', max_length=20, verbose_name='严重程度')),
                ('message', models.TextField(verbose_name='问题描述')),
                ('expected_value', models.JSONField(blank=True, null=True, verbose_name='预期状态')),
                ('actual_value', models.JSONField(blank=True, null=True, verbose_name='实际状态')),
                ('status', models.CharField(choices=[('open', '待处理'), ('ignored', '已忽略'), ('resolved', '已解决')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_continuity_issues', to='workflows.shot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuity_issues', to='projects.project')),
                ('to_shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_continuity_issues', to='workflows.shot')),
            ],
            options={'db_table': 'continuity_issues', 'ordering': ['from_shot__scene__number', 'from_shot__number', 'category']},
        ),
        migrations.AddConstraint(model_name='productionentity', constraint=models.UniqueConstraint(fields=('project', 'entity_type', 'name'), name='uniq_prod_entity_project_type_name')),
        migrations.AddIndex(model_name='productionentity', index=models.Index(fields=['project', 'entity_type'], name='prod_entity_proj_type_idx')),
        migrations.AddConstraint(model_name='productionscene', constraint=models.UniqueConstraint(fields=('project', 'number'), name='uniq_prod_scene_project_number')),
        migrations.AddIndex(model_name='productionscene', index=models.Index(fields=['project', 'number'], name='prod_scene_proj_number_idx')),
        migrations.AddConstraint(model_name='shot', constraint=models.UniqueConstraint(fields=('scene', 'number'), name='uniq_prod_shot_scene_number')),
        migrations.AddIndex(model_name='shot', index=models.Index(fields=['canvas', 'canvas_node_key'], name='prod_shot_canvas_node_idx')),
        migrations.AddIndex(model_name='shot', index=models.Index(fields=['scene', 'number'], name='prod_shot_scene_number_idx')),
        migrations.AddConstraint(model_name='shotentitybinding', constraint=models.UniqueConstraint(fields=('shot', 'entity'), name='uniq_shot_entity_binding')),
        migrations.AddConstraint(model_name='shottake', constraint=models.UniqueConstraint(fields=('shot', 'number'), name='uniq_shot_take_number')),
        migrations.AddConstraint(model_name='shottake', constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('shot',), name='uniq_shot_final_take')),
        migrations.AddConstraint(model_name='continuityissue', constraint=models.UniqueConstraint(fields=('from_shot', 'to_shot', 'category'), name='uniq_continuity_shot_pair_cat')),
    ]
